on:
  pull_request:
    branches:
      - main

jobs:
  run_checks:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Run stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: nofilter

      - name: Fail linter if necessary
        run: yarn stylelint

      - name: Fail eslint if necessary
        run: yarn lint

#      - name: Run Cypress
#        run: yarn test
#        env:
#          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
